[package]
name = "awc-dns-resolver-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-tls = "3.1.1"
actix-web = "4.4.0"
awc = "3.2.0"
futures-util = "0.3.28"
trust-dns-resolver = "0.23.0"
